project:
  type: website

website:
  title: "Preston-Smith203"
  navbar:
    left:
      - href: index.qmd
        text: SE Book
      - href: FB.qmd
        text: Fuzzing Book

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true



