---
title: "Professional Précis Debugging Book"
subtitle: "Preston Smith"
---

## **DB1** Introduction to Debugging

The first chapter of the debugging book mostly goes over the basics of debugging and different ways to detect a bug it talks
about printf debugging which is when you put print statements in your code to help you keep track of what's going on it mentions
this method is very inefficient. It also talks about that when debugging you need to solve the cause not the symptom so if you see
a bug for a certain input you can't just fix it for that specific input you need to fix the problem in general which means finding the
root cause. Which this chapter suggests doing through the scientific method ask a question of why something isn't working come up with
a theory figure out how you can test it test it and repeat until you find the issue.

### Use-case

This is obviously useful because it just broad debugging concepts and thing to keep in mind when doing it. It's not something you can't
really figure out on your own and there's nothing in this chapter that is particurly complicated so implmenting the concepts can be almost
immediate if they aren't already.

## **DB2** Tracing Executions

Tracing a programs execution is to help with debugging by showing the step the program took when running and if there was a crash it allows
you to look through the steps and see where it failed and fix the root cause of the problem more effectivly a simple way you can do this
is to use sys.settrace() function which traces everyline of code run and prints it but this can sometimes give you to much information so you
may want something a little more limited. an example of this

```python
def remove_html_markup_traced(s):  # type: ignore
    sys.settrace(traceit)
    ret = remove_html_markup(s)
    sys.settrace(None)
    return ret
```
This will trace the the remove_html_markup function and print out the results even if the code crashes it will show you everything that ran.
As stated before this is very useful because it makes finding the cause of a bug significantly easier and more convenient.

### Use-case

At least with chasten most of the test cases actually do get traced in fact the ones that use hypothesis are automaticlly traced by hypothesis so this type of thing is already for the most part implemented. So all we really would want is have non hypothesis functions traced but other than that this concept is already implemented for the most part.

## **DB3** Assertions

Assert statements are very useful when it comes to debugging as they can make writing test cases very easy by leveraging things that should be true. So in the case of test cases if you know what the output should be you can use an assert statement that will throw an error if the output isn't what is expected an example of this in the debugging book is

```python
def test_square_root() -> None:
    assert square_root(4) == 2
    assert square_root(9) == 3
```

This is testing a function that finds the square root of numbers and leverages the fact that 4 and 9 are perfect squares and we know what the
square root should be. So it's checking that the output is what's expected and that it's finding the square root properly.

Another way they can be used is a form of debug handling in the following example there used to check to make sure that the provided input
isn't a negative number and to check that the result of the computation is close to the expected value by utilizing the math module. If the
code doesn't fit these criteria it will throw an **AssertionError** and stop running

```python
def square_root(x):  # type: ignore
    assert x >= 0  # precondition

    approx = None
    guess = x / 2
    while approx != guess:
        approx = guess
        guess = (approx + x / approx) / 2

    assert math.isclose(approx * approx, x)
    return approx
```

### Use-case

We already use a ton of assert statements in test cases as they are easy to use and make checking things alot simpler. We don't really use them for debug handling and exampled in the debugging book nor do we really need to but it is a way they can be used. Since for the most part we already use assert statements I don't really think there is anything we can implement that's new from this chapter of the debugging book but it may be useful in the future.

## **DB4** Statistical Debugging (Automatic Fault Localization)

The idea of Statistical Debugging is kind of self explanatory it's the idea that when you have a program that doesn't always run you can manually or have a program automatically run it and try to find a correlation between the failures and a specific part of the program whether it's just a single line or if something isn't being covered in tested it may be considered a possibility. The idea is to trace code
when it's being run and find similaritys between failures to narrow down the cause it's a similar concept to reducing failute inducing inputs
in the fuzzing book.

```python
def code_with_coverage(function: Callable, coverage: Coverage) -> None:
    source_lines, starting_line_number = \
       getsourcelines(function)

    line_number = starting_line_number
    for line in source_lines:
        marker = '*' if (function, line_number) in coverage else ' '
        print(f"{line_number:4} {marker} {line}", end='')
        line_number += 1
```

Coverage is heavily used in this process as it tells what lines where run and what weren't which can be used to help to determine the pausible cause of failure like maybe it only fails if line 3 is run so it can determine a large correlation between the line and the code
crashing. The above function printing which lines are run and you can use something like this to help analyze what's going. So in a way all
this concept is statistical analysis trying to find a correlation between something.

### Use-case

This is useful in a very general sense as it's an important process in debugging in general and just running the code and seeing what happens
can a encompass this concept in a general sense so in that way these concept are already use but having code automatically run seems like It
would have to be a future endeavor as a lot of things already set up do some of this already and normal tracing achieves a lot of the same functionallity just without the reduction in data. So it would be a cool thing to implement in the future but not with the time we have left to work on the projects.